version: "3"

services:
  # main bot app
  igor-bot-app:
    image: containinger/igor-bot:latest
    container_name: igor-bot-app
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
    restart: unless-stopped
    depends_on:
      - igor-bot-db
    environment:
      - TZ=Europe/Vienna
      - Bot__Discord__Token=<bot-token-here>
    labels:
      - traefik.enable=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB to keep state
  igor-bot-db:
    image: mongo:5
    container_name: igor-bot-db
    restart: unless-stopped
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/config:/data/configdb
    environment:
      - TZ=Europe/Vienna
    labels:
      - traefik.enable=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB Web Admin UI (optional)
  igor-bot-db-ui:
    image: ugleiton/mongo-gui:latest
    container_name: igor-bot-db-ui
    restart: unless-stopped
    depends_on:
      - igor-bot-db
    environment:
      - TZ=Europe/Vienna
      - MONGO_URL=mongodb://igor-bot-db:27017
    ports:
      - 127.0.0.1:8081:4321
    labels:
      - traefik.enable=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"
